from playwright.sync_api import Page,expect

def test_dropdown(page:Page):
    page.goto("https://demoqa.com/automation-practice-form")
    page.get_by_placeholder("First Name").fill("sana")
    page.get_by_placeholder("Last Name").fill("dubbaka")
    page.locator("#userEmail").fill("sana@gmail.com")
    page.get_by_label("Female").check()
    page.get_by_placeholder("Mobile Number").fill("1231231231")
    page.locator("#dateOfBirthInput").click()
    page.locator(".react-datepicker__year-select").select_option("2000")
    page.locator(".react-datepicker__month-select").select_option("August")
    page.locator("div[aria-label='Choose Saturday, August 5th, 2000']").click()
    page.locator(".subjects-auto-complete__input-container").click()
    page.locator("#subjectsInput").fill("Maths")
    page.locator("#subjectsInput").press("Enter")
    page.get_by_label("Music").check()
    page.locator("#uploadPicture").set_input_files("C:\\Users\\Gayathri\\OneDrive\\Documents\\Gayathri_Dubbaka_CV_ QA.docx")
    page.locator("#state > .css-13cymwt-control > .css-hlgwow > .css-19bb58m").click()
    page.get_by_role("option", name="Haryana").click()
    page.locator("#city > .css-13cymwt-control > .css-hlgwow > .css-19bb58m").click()
    page.get_by_role("option", name="Karnal").click()
    page.get_by_placeholder("Current Address").fill("rajnagar colony")
    page.get_by_role("button",name="Submit").click()
    page.get_by_role("button", name="Close").click()
    page.wait_for_timeout(3000)